const STORE_USER_INFO = 'STORE_USER_INFO'
const STORE_AUTH_TOKEN = 'STORE_AUTH_TOKEN'
const STORE_AUTH_TOKEN_TYPE = 'STORE_AUTH_TOKEN_TYPE'
const TOTAL_CART_PRODUCT = 'TOTAL_CART_PRODUCT'
const IS_LOGIN = 'IS_LOGIN'
//OpenSans, OpenSans-Semibold

export { STORE_USER_INFO, STORE_AUTH_TOKEN, STORE_AUTH_TOKEN_TYPE,TOTAL_CART_PRODUCT,IS_LOGIN}
